"use client";
import { useEffect, useState } from "react";
import { fetchWithTimeout } from "./api-client.mjs";
type Trade={id:string;symbol:string;interval:string;direction:string;status:string;entry_price:number;current_price:number;exit_price:number|null;return_pct:number|null;unrealized_pct:number;config_revision?:string;runtime_config?:unknown;opened_at:number;closed_at?:number;exit_reason:string;fee_rate?:number};
export default function PaperLedger(){
 const [trades,setTrades]=useState<Trade[]>([]),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 useEffect(()=>{let active=true;async function load(){try{const res=await fetchWithTimeout('/api/paper-trades');if(!res.ok)throw Error('读取模拟记录失败');const data=await res.json() as {trades:Trade[]};if(active){setTrades(data.trades);setError('');setLoaded(true);}}catch(e){if(active)setError(String(e));}}void load();const id=setInterval(load,15000);return()=>{active=false;clearInterval(id);};},[]);
 const shown=trades.filter(t=>filter==='all'||t.status===filter).sort((a,b)=>b.opened_at-a.opened_at);
 return <section className="view-stack"><div className="view-intro"><div><h2>模拟交易记录</h2><p>信号触发后本地记账，按照记录的止损和止盈退出。未向交易所发单。</p><p>收益为单笔扣手续费后的比例；不代表账户净值，也未模拟盘口成交和资金费。</p></div></div><section className="content-panel"><label>记录筛选 <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部保留记录</option><option value="open">持仓中</option><option value="closed">已退出</option></select></label><p role="status">{error||(!loaded?'读取中…':`${shown.length} 条记录`)}</p>{shown.map(t=><details key={t.id} className="report-row"><summary>{t.symbol} · {t.interval} · {t.direction==='long'?'做多':'做空'} · {t.status==='open'?'持仓中':'已退出'} · {((t.status==='open'?t.unrealized_pct:t.return_pct??0)*100).toFixed(2)}%</summary><p>开仓 {t.entry_price} → {t.status==='open'?t.current_price:t.exit_price} · {new Date(t.opened_at*1000).toLocaleString('zh-CN')} · {t.exit_reason}</p><p>配置版本：{t.config_revision||'历史记录未保存版本'} · 单边手续费：{t.fee_rate===undefined?'历史默认':`${t.fee_rate*100}%`}</p>{t.runtime_config!==undefined&&<pre>{JSON.stringify(t.runtime_config,null,2)}</pre>}</details>)}{loaded&&!shown.length&&!error&&<div className="empty-state">尚无符合条件的模拟记录；等待有效信号触发。</div>}</section></section>;
}
